# Compose file for integration testing. Builds processor orchestrator and runs tests.
version: "3.8"
services:
  processor-orchestrator:
    build:
      context: ..
      target: lint
    container_name: processor-orchestrator_container