version: "3.8"

services:
  video-forwarder:
    build:
      context: ..
      target: testing
    environment:
      SEGMENT_SIZE: 2
      SEGMENT_AMOUNT: 5
      CONFIG_PATH: /app/NetworkConfig.json
      STREAM_FOLDER: /app/streams
      ENCODING: libx264
  video-forwarder_test:
    build:
      context: ..
      target: test_integration
    container_name: video-forwarder_container
    depends_on:
      - "video-forwarder"
