version: "3.2"

services:
  interface:
    image: tt-interface-image
    ports:
      - published: 50007
      - target: 5000
  forwarder1:
    image: tt-forwarder-image
    ports:
      - published: 50008
      - target: 8080
      - mode: "host"

