version: '3.2'

services:
  agent:
    image: portainer/agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - portainer
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]

  portainer:
    image: portainer/portainer-ce
    command: -H tcp://tasks.agent:9001 --tlsskipverify --ssl --sslcert /run/secrets/tracktech.ml-cert.pem --sslkey /run/secrets/tracktech.ml-privkey.pem
    ports:
      - '50003:9000'
      - '50004:8000'
    volumes:
      - portainer_data:/data
    networks:
      - portainer
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
    secrets:
        - tracktech.ml-cert.pem
        - tracktech.ml-privkey.pem

networks:
  portainer:
    driver: overlay
    attachable: true

secrets:
  tracktech.ml-cert.pem:
    external: true
  tracktech.ml-privkey.pem:
    external: true

volumes:
  portainer_data: