version: "3.2"

services:
  registry:
    image: registry
    restart: always
    ports:
      - published: 50007
      - target: 5000
  environment:
     - REGISTRY_HTTP_TLS_CERTIFICATE=/run/secrets/tracktech.ml-cert.pem 
     - REGISTRY_HTTP_TLS_KEY=/run/secrets/tracktech.ml-key.pem 
    
secrets:
  tracktech.ml-cert.pem:
    external: true
  tracktech.ml-privkey.pem:
    external: true