version: "3.2"

services:
  interface:
    image: tt-interface-image
    ports:
      - published: 50007
      - target: 5000
    entrypoint: ["serve", "-s", "build", "--ssl-cert","/run/secrets/tracktech.ml-cert.pem","--ssl-key","/run/secrets/tracktech.ml-privkey.pem"]
  forwarder1:
    image: tt-forwarder-image
    ports:
      - published: 50008
      - target: 8080
      - mode: "host"

secrets:
  tracktech.ml-cert.pem:
    external: true
  tracktech.ml-privkey.pem:
    external: true