image: "python:3.8.8"

before_script:
  - cd CameraProcessor
  - mkdir docs/html
  - python --version
  - pip install -r ./requirements.txt

stages:
  - documentation

pdoc-documentation:
  stage: documentation
  script:
    - cd CameraProcessor
    - python src/documentation.py
  artifacts:
    when: always
    paths:
    - CameraProcessor/docs/html/