image: "python:3.8.8"

before_script:
  - sudo apt-get update
  - sudo apt-get install -y libgl1-mesa-dev
  - python --version
  - pip install virtualenv
  - python -m venv venv
  - pip install -r CameraProcessor/requirements.txt

stages:
  - test

pytest:
  stage: test
  script:
    - cd CameraProcessor
    - python -m pytest tests --junitxml=report.xml
  artifacts:
    when: always
    paths: 
    - CameraProcessor/report.xml
    reports:
      junit: CameraProcessor/report.xml
