processor_build:
  stage: build
  script:
    - docker-compose -f ./CameraProcessor/compose/docker-compose_test.yml up --build --no-start
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      changes:
        - CameraProcessor/**/*
      when: always
    - if: '$project =~ /processor/'
      when: always
    - if: '$stage =~ /build/'
      when: always
        
processor_test_unit:
  stage: test
  script:
    - docker-compose -f ./CameraProcessor/compose/docker-compose_test_unit.yml up --build
    - docker cp camera-processor_container:/app/cp-unit-report.xml cp-unit-report.xml
    - docker cp camera-processor_container:/app/coverage_html cp-coverage_html
  after_script:
    - docker-compose -f ./CameraProcessor/compose/docker-compose_test_unit.yml down
  coverage: /^TOTAL.*\s+(\d+\%)$/
  artifacts:
    reports:
      junit: cp-unit-report.xml
    paths:
      - cp-coverage_html
    when: always 
    expire_in: 10 days
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      changes:
        - CameraProcessor/**/*
      when: always
    - if: '$project =~ /processor/'
      when: always
    - if: '$stage =~ /test/'
      when: always
  
processor_test_integration_video-forwarder:
  stage: test
  script:
    - docker-compose -f ./CameraProcessor/compose/docker-compose+forwarder.yml up --build --exit-code-from camera-processor-test-service
    - docker cp processor-forwarder-integration-test-container:/app/cp-vf-integration-report.xml cp-vf-integration-report.xml
  after_script:
    - docker-compose -f ./CameraProcessor/compose/docker-compose+forwarder.yml down
  artifacts:
    reports:
      junit: cp-vf-integration-report.xml
    when: always
    expire_in: 10 days
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      changes:
        - CameraProcessor/**/*
      when: always
    - if: '$project =~ /processor/'
      when: always
    - if: '$stage =~ /test/'
      when: always

processor_test_integration_orchestrator:
  stage: test
  script:
    - docker-compose -f ./CameraProcessor/compose/docker-compose+orchestrator.yml up --build --exit-code-from camera-processor-test-service
    - docker cp processor-integration-test-container:/app/cp-po-integration-report.xml cp-po-integration-report.xml
  after_script:
    - docker-compose -f ./CameraProcessor/compose/docker-compose+orchestrator.yml down
  artifacts:
    reports:
      junit: cp-po-integration-report.xml
    when: always
    expire_in: 10 days
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      changes:
        - CameraProcessor/**/*
      when: always
    - if: '$project =~ /processor/'
      when: always
    - if: '$stage =~ /test/'
      when: always

processor_lint:
  stage: lint
  script:
    - docker-compose -f ./CameraProcessor/compose/docker-compose_lint.yml up --build --no-start
    - docker cp .pylintrc camera-processor_lint_container:/app
    - docker cp utility/pylint_ignore.py camera-processor_lint_container:/app/utility
    - docker cp utility/__init__.py camera-processor_lint_container:/app/utility
    - docker-compose -f ./CameraProcessor/compose/docker-compose_lint.yml up
  after_script:
    - docker-compose -f ./CameraProcessor/compose/docker-compose_lint.yml down
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      changes:
        - CameraProcessor/**/*
      when: always
    - if: '$project =~ /processor/'
      when: always
    - if: '$stage =~ /lint/'
      when: always
