image: "python:3.8.8"

before_script:
  - cd CameraProcessor
  - mkdir docs/html
  - python --version
  - pip install -r ./requirements.txt

stages:
  - documentation
  - deploy_pages

pdoc_documentation:
  stage: documentation
  variables:
    PYTHONPATH: "/usr/app/src"
  script:
    - ls
    - python src/documentation.py
  artifacts:
    when: always
    paths:
    - CameraProcessor/docs/html/
    expire_in: 14 days

deploy_documentation_gitlab_pages:
  stage: deploy_pages
  needs:
    - job: pdoc_documentation # only deploy when docs creation succeeded
  script:
    - mv CameraProcessor/docs/html/ public/$BRANCH/CameraProcessor
  artifacts:
    paths:
      - public
    expire_in: 14 days