image: "python:3.8.8"

before_script:
  - python --version
  - pip install -r requirements.txt

stages:
  - test

pytest:
  stage: test
  script:
    - python -m pytest tests --junitxml=report.xml
  artifacts:
    when: always
    reports:
      junit: report.xml
