version: '3.8'

services:
  cameraprocessor:
    build:
      context: .
    environment:
      ORCHESTRATOR_URL: "ws://tracktech.ml:50010/processor"
      HLS_STREAM_URL: "http://81.83.10.9:8001/mjpg/video.mjpg"
      PROCESSOR_MODE: "deploy"
      DETECTION_ALG: "yolov5"
      TRACKING_ALG: "sort"
      REID_ALG: "torchreid"
#    deploy:
#      resources:
#        reservations:
#          devices:
#            - capabilities: [gpu]
