version: "3"

services:
  camera-processor-test-service:
    image: camera-processor-test:latest
    container_name: camera-processor-integration-test-container
    command: ["python3.8", "-m", "pytest", "tests/integrationtests", "--junitxml=report.xml"]
    deploy:
      replicas: 1
#      resources:
#        reservations:
#          devices:
#            - capabilities: [ gpu ]

  processor-orchestrator-test-service:
    image: processor-orchestrator:latest
    command: ["python3.8", "src/main.py"]
    deploy:
      replicas: 1
