# Compose file for integration testing. Builds processor orchestrator build image from source, takes camera-processor image from
version: "3.4"
services:
  # Take the already built test container from the camera processor
  camera-processor-test-service:
    image: camera-processor:latest
    container_name: processor-integration-test-container
    depends_on:
      - "forwarder-test-service"
    # Overwrite entrypoint to run integration tests instead
    entrypoint: ["python3.8", "-m", "pytest", "/app/tests/forwarderintegrationtests" ,"--junitxml=cp-f-integration-report.xml"]
  # Build the build stage from the processor orchestrator manually (since it is not yet done in pipeline)
  forwarder-test-service:
    build:
      context: ../VideoForwarder
      target: production
    container_name: ext-forwarder-integration-test-container
