version: "3"
 
services:
  camera-processor-test-service:
    image: camera-processor
    ports:
      - 9090:9090
      - 8000:8000
    command: ["python", "src/websocket_client.py"]
    deploy:
      replicas: 1
 
  processor-orchestrator-test-service:
    image: processor-orchestrator
    ports:
      - 8000:80
    deploy:
      replicas: 1
