# Compose file for integration testing. Builds processor orchestrator build image from source, takes camera-processor image from
version: "3.4"
services:
  # Take the already built test container from the camera processor
  camera-processor-test-service:
    image: camera-processor-test:latest
    container_name: processor-integration-test-container
    # Overwrite entrypoint to run integration tests instead
    entrypoint: ["python3.8", "-m", "pytest", "tests/integrationtests" ,"--junitxml=integration-report.xml"]
  # Build the build stage from the processor orchestrator manually (since it is not yet done in pipeline)
  processor-orchestrator-service:
    build:
      context: ../ProcessorOrchestrator
      target: build
    container_name: ext-orchestrator-integration-test-container
