FROM python:3.8-slim-buster

# Keeps Python from generating .pyc files in the container
ENV PYTHONDONTWRITEBYTECODE=1

# Turns off buffering for easier container logging
ENV PYTHONUNBUFFERED=1

RUN apt update
RUN apt install -y ffmpeg

WORKDIR /app
ENV PYTHONPATH=/app

# Install pip requirements
COPY requirements-test.txt .
RUN ["python3.8", "-m", "pip", "install", "-r", "requirements-test.txt"]

COPY data/annotated/test data/annotated/test
COPY src src
COPY tests tests
