# Compose file for integration testing. Builds processor orchestrator build image from source, takes camera-processor image from
version: "3.4"
services:
  # Take the already built test container from the camera processor
  camera-processor-service:
    image: camera-processor-test:latest
    container_name: processor-integration-test-container
    # Second command is to keep the container alive after running tests
    entrypoint: bash -c "python3.8 -m pytest tests/integrationtests --junitxml=report.xml && tail -f /dev/null"
  # Build the build stage from the processor orchestrator manually (since it is not yet done in pipeline)
  processor-orchestrator-test-service:
    build:
      context: ../ProcessorOrchestrator
      target: build
    container_name: ext-orchestrator-integration-test-container
