# Compose file for integration testing. Builds processor orchestrator build image from source, takes camera-processor image from
version: "3.9"
services:
  # Take the already built test container from the camera processor
  camera-processor-service:
    image: camera-processor-test:latest
    container_name: cp-po-processor-integration-test-container
    command: ["python3.8", "-m", "pytest", "tests/integrationtests", "--junitxml=report.xml"]
  # Build the build stage from the processor orchestrator manually (since it is not yet done in pipeline)
  processor-orchestrator-test-service:
    build:
      context: ../ProcessorOrchestrator
      target: build
    container_name: cp-po-orchestrator-integration-test-container
