version: '3.8'

services:
  cameraprocessor:
    build:
      context: .
    environment:
      ORCHESTRATOR_URL: "ws://tracktech.ml:50010/processor"
      FORWARDER_URL: "https://tracktech.ml:50008/stream.m3u8"
      PROCESSOR_MODE: "deploy"
      DETECTION_ALG: "yolov5"
      TRACKING_ALG: "sort"
      REID_ALG: "torchreid"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]