FROM python:3.8-slim-buster AS docbuild

# Keeps Python from generating .pyc files in the container
ENV PYTHONDONTWRITEBYTECODE=1

# Turns off buffering for easier container logging
ENV PYTHONUNBUFFERED=1

RUN apt update

WORKDIR /app
ENV PYTHONPATH=/app

# Install pip requirements
COPY requirements-docs.txt .
RUN ["python3.8", "-m", "pip", "install", "-r", "requirements-docs.txt"]


FROM docbuild AS testbuild

RUN apt install -y ffmpeg
# Install pip requirements
COPY requirements-test.txt .
RUN ["python3.8", "-m", "pip", "install", "-r", "requirements-test.txt"]

COPY data/annotated/test data/annotated/test
COPY src src
COPY tests tests

