version: "3"
 
services:
  camera-processor-test-service:
    image: camera-processor
    ports:
      - 9090:9090
    command: ["python", "src/websocket_client.py",
              "--ws-url", "ws://processor-orchestrator-test-service/processor"]
    deploy:
      replicas: 1
 
  processor-orchestrator-test-service:
    image: processor-orchestrator
    ports:
      - 80:80
    deploy:
      replicas: 1
