version: "3"

services:
  camera-processor-yolov5-service:
    image: camera-processor-yolov5:latest
    ports:
      - 9090:9090
    command: ["python3.8", "src/main.py"]
    deploy:
      replicas: 1
      resources:
        reservations:
          devices:
            - capabilities: [ gpu ]

  processor-orchestrator-service:
    image: processor-orchestrator:latest
    ports:
      - 80:80
    deploy:
      replicas: 1
