name: Orchestrator Build

on:
  push:
    paths:
      - .github/workflows/Orchestrator/Orchestrator_Build.yml
  pull_request:
    paths:
      - ProcessorOrchestrator/**

jobs:
  interface_build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: docker-compose -f ./ProcessorOrchestrator/docker-compose.yml build
      - name: Remove
        run: docker-compose -f ./ProcessorOrchestrator/docker-compose.yml rm
