# Compose file for integration testing. Builds processor orchestrator build image from source, takes camera-processor image from
version: "3.4"
services:
  # Take the already built test container from the camera processor
  camera-processor-test-service:
    build:
      context: ..
      target: test_integration_forwarder
    container_name: processor-forwarder-integration-test-container
    depends_on:
      - "forwarder-test-service"
  # Build the build stage from the forwarder manually (since it is not yet done in pipeline)
  forwarder-test-service:
    build:
      context: ../../VideoForwarder
      target: development
    environment:
      CAMERA_URL: rtmp://localhost/stream
      CAMERA_AUDIO: "false"
      STREAM_LOW: "true"
    container_name: ext-forwarder-integration-test-container
    # Healthcheck so test doesn't start too soon and no timeout is required
    healthcheck:
      test: curl --fail -s http://localhost/stream.m3u8 || exit 1
      interval: 10s
      timeout: 5s
      retries: 6
