# The compose file for integration testing. Builds processor orchestrator build image from source, takes camera-processor image from.
version: "3.4"
services:
  # Take the already built test container from the camera processor.
  camera-processor-test-service:
    build:
      context: ..
      target: test_integration_orchestrator
    container_name: processor-integration-test-container
    depends_on:
      - "processor-orchestrator-service"
    # Overwrite entrypoint to run integration tests instead.
  # Build the build stage from the processor orchestrator manually (since it is not guaranteed the last develop version on the runner).
  processor-orchestrator-service:
    build:
      context: ../../ProcessorOrchestrator
      target: build
    container_name: ext-orchestrator-integration-test-container
