#stages:
#  - build
#  - test
#
#docker_build:
#  stage: build
#  script:
#    - docker build -t processor-orchestrator --target testing ./ProcessorOrchestrator
#  rules:
#    - if: $CI_MERGE_REQUEST_ID
#    - changes:
#        - /*
#
#unit-testing:
#  stage: test
#  needs: [docker_build]
#  script:
#    - docker run processor-orchestrator
#  rules:
#    - if: $CI_MERGE_REQUEST_ID
#    - changes:
#        - /*
