stages:
  - build

docker-build:
  # Official docker image.
  image: docker:latest
  stage: build
  services:
    - docker:dind
  script:
    - docker build -t processor-orchestrator .
    - docker run processor-orchestrator
