stages:
  - build

docker-build:
  # Official docker image.
  image: docker:latest
  stage: build
  services:
    - docker:dind
  script:
    - docker build -t processor-orchestrator ./ProcessorOrchestrator
    # - docker run processor-orchestrator
  rules:
    - if: $CI_MERGE_REQUEST_ID
