stages:
  - build
  - test

docker_build:
  # Official docker image.
  image: docker:latest
  stage: build
  services:
    - docker:dind
  script:
    - docker build -t processor-orchestrator --target testing ./ProcessorOrchestrator
  rules:
    - if: $CI_MERGE_REQUEST_ID
    - changes:
        - /*

unit-testing:
  stage: test
  needs: [docker_build]
  script:
    - docker run processor-orchestrator
  rules:
    - if: $CI_MERGE_REQUEST_ID
    - changes:
        - /*
