version: "3.8"

services:
  orchestrator:
    image: tracktech.ml:50007/tt-orchestrator-image
    build: .
    ports:
      - published: 80
        target: 80
      - published: 443
        target: 443