# Compose file for integration testing. Builds processor orchestrator and runs tests.
version: "3.8"
services:
  processor-orchestrator-service:
    # Use the existing testing image, but actually run the application
    image: processor-orchestrator:latest
    container_name: processor-orchestrator-service
    entrypoint: ["pytest","testing/testing_server.py","--cov-config=.coveragerc", "--cov=src", "--cov-report=html", "--cov-report=term"]
  processor-orchestrator-integration-tests:
    # Use the existing testing image again, but run integration tests
    depends_on:
      - processor-orchestrator-service
    image: processor-orchestrator:latest
    container_name: processor-orchestrator-integration-tests
    entrypoint: ["pytest", "testing/integration_testing", "--junitxml=integration-report.xml"]