interface_build:
  stage: build
  script:
    - docker-compose -f Interface/docker-compose.yml build
  after_script:
    - docker-compose -f Interface/docker-compose.yml down
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      changes:
        - Interface/**/*
      when: always
    - if: '$project =~ /interface/'
      when: always
    - if: '$stage =~ /build/'
      when: always

interface_test_unit:
  stage: test
  script:
    - docker-compose -f Interface/compose/docker-compose_test_unit.yml up --build --exit-code-from interface
    - docker cp interface_container:/react/coverage i-coverage
  after_script:
    - docker-compose -f Interface/compose/docker-compose_test_unit.yml down
  artifacts:
    when: always
    paths:
      - i-coverage
    expire_in: 5 days
  coverage: /All\sfiles.*?\s+(\d+.\d+)/
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      changes:
        - Interface/**/*
      when: always
    - if: '$project =~ /interface/'
      when: always
    - if: '$stage =~ /test/'
      when: always

interface_test_integration:
  stage: test
  script:
    - docker-compose -f Interface/compose/docker-compose_test_integration.yml up --build --exit-code-from interface
    - docker cp interface_container:/react/coverage i-coverage
  after_script:
    - docker-compose -f Interface/compose/docker-compose_test_integration.yml down
  artifacts:
    when: always
    paths:
      - i-coverage
    expire_in: 5 days
  coverage: /All\sfiles.*?\s+(\d+.\d+)/
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      changes:
        - Interface/**/*
      when: always
    - if: '$project =~ /interface/'
      when: always
    - if: '$stage =~ /test/'
      when: always

interface_lint:
  stage: lint
  script:
    - docker-compose -f Interface/compose/docker-compose_lint.yml up --build --exit-code-from interface
  after_script:
    - docker-compose -f Interface/compose/docker-compose_lint.yml down
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      changes:
        - Interface/**/*
      when: always
    - if: '$project =~ /interface/'
      when: always
    - if: '$stage =~ /lint/'
      when: always