# Installation
FROM python:3.8-slim-buster

# Keeps Python from generating .pyc files in the container
ENV PYTHONDONTWRITEBYTECODE=1

# Turns off buffering for easier container logging
ENV PYTHONUNBUFFERED=1

WORKDIR /app
ENV PYTHONPATH=/app

# Install python dependencies
RUN ["python3.8", "-m", "pip", "install", "-U", "selenium"]
RUN ["python3.8", "-m", "pip", "install", "unittest2"]
RUN ["python3.8", "-m", "pip", "install", "subprocess.run"]
RUN ["python3.8", "-m", "pip", "install", "pylint==2.6.0"]

# Copy the source code
COPY testingSelenium testingSelenium
RUN ["mkdir", "utility"]

WORKDIR /