# Compose file for integration testing. Builds processor orchestrator build image from source.
version: "3.4"
services:
  # Take the already built test container from the camera processor
  interface-test-service:
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: interface-integration-test-container
    depends_on:
      - "processor-orchestrator-service"
    # Overwrite entrypoint to run integration tests instead
    entrypoint: ["npm", "test", "--", "--coverage", "testing/integration testing"]
  # Build the build stage from the processor orchestrator manually (since it is not guaranteed the last develop version on the runner)
  processor-orchestrator-service:
    build:
      context: ../ProcessorOrchestrator
      target: build
    container_name: processor-orchestrator-service