FROM node:15 AS builder
WORKDIR /react
COPY react/package.json ./package.json
COPY react/package-lock.json ./package-lock.json
RUN ["npm","install"]
COPY react/babel.config.json ./babel.config.json
COPY react/jest.config.js ./jest.config.js
COPY react/tsconfig.json ./tsconfig.json
COPY react/styleMock.js ./styleMock.js
COPY react/setupJest.js ./setupJest.js

COPY react/public ./public
COPY react/src ./src
COPY react/testing ./testing

# copy static files
COPY testconfig.json /build/config.json

ENTRYPOINT ["npm", "test", "--", "--coverage"]