FROM node:15 AS builder
WORKDIR /react
COPY react/package.json ./package.json
COPY react/package-lock.json ./package-lock.json
COPY react/.eslintrc.json ./.eslintrc.json
RUN ["npm","install"]

COPY react/public ./public
COPY react/src ./src
COPY react/testing ./testing

ENTRYPOINT ["./node_modules/.bin/eslint", "src/*.tsx", "src/*.ts"]