FROM python:3.8-slim-buster

WORKDIR /app
ENV PYTHONPATH=/app

RUN ["python3.8", "-m", "pip", "install", "-U", "selenium"]
RUN ["python3.8", "-m", "pip", "install", "time"]
RUN ["python3.8", "-m", "pip", "install", "unittest"]
RUN ["python3.8", "-m", "pip", "install", "subprocess"]
RUN ["python3.8", "-m", "pip", "install", "pylint"]

COPY testingSelenium testingSelenium
RUN ["mkdir", "utility"]

WORKDIR /