version: "3.8"

services:
  forwarder:
    build: .
    environment:
      SEGMENT_SIZE: 2
      SEGMENT_AMOUNT: 5
      CONFIG_PATH: /app/NetworkConfig.json
      STREAM_FOLDER: /app/streams
      ENCODING: libx264
    ports:
      - published: 80
        target: 80
      - published: 443
        target: 443
