# Installation
FROM python:3.8-slim-buster

# Keeps Python from generating .pyc files in the container
ENV PYTHONDONTWRITEBYTECODE=1

# Turns off buffering for easier container logging
ENV PYTHONUNBUFFERED=1

WORKDIR /app
ENV PYTHONPATH=/app

# Install python dependencies
COPY requirements.txt .
RUN ["python3.8", "-m", "pip", "install", "-r", "requirements.txt"]
RUN ["python3.8", "-m", "pip", "install", "pylint==2.6.0"]

# Copy a test config
COPY NetworkConfig.json /NetworkConfig.json

# Copy the source code
COPY src src
RUN ["mkdir", "utility"]

WORKDIR /