version: "3.8"

services:
  forwarder:
    build: .
    environment:
      CAMERA_AUDIO: "true"
      CAMERA_URL: rtsp://wowzaec2demo.streamlock.net/vod/mp4:BigBuckBunny_115k.mov
      STREAM_FOLDER: /app/streams
      STREAM_ENCODING: libx264
      SEGMENT_SIZE: 2
      SEGMENT_AMOUNT: 5
    ports:
      - published: 80
        target: 80
      - published: 443
        target: 443
