version: '3.8'

services:
  forwarder:
    build:
      context: .
      target: development
    environment:
      CAMERA_URL: rtmp://localhost/stream
      CAMERA_AUDIO: 'false'
      STREAM_LOW: 'true'
    ports:
      - published: 80
        target: 80
