version: "3.8"

services:
  forwarder:
    image: tracktech.ml:50007/tt-forwarder-image
    build: .
    environment:
      SEGMENT_SIZE: 2
      SEGMENT_AMOUNT: 5
      CONFIG_PATH: /NetworkConfig.json
      STREAM_FOLDER: /streams
      ENCODING: libx264
    ports:
      - 80:80
  forwarder-docs:
    image: tracktech.ml:50007/tt-forwarder-docs-image
    build:
      context: .
      target: pdoc
    ports:
      - 8080:8080