_BASE_: fastreid/configs/Base-SBS.yml

MODEL:
  WEIGHTS: market_sbs_R101-ibn.pth
  DEVICE: cpu
  BACKBONE:
    DEPTH: 101x
    WITH_IBN: True

DATASETS:
  NAMES: ("Market1501",)
  TESTS: ("Market1501",)
