version: 0.1
log:
  accesslog:
    disabled: true
  level: debug
storage:
  cache:
    blobdescriptor: inmemory
  filesystem:
    rootdirectory: /var/lib/registry
auth:
  htpasswd:
    realm: Registry Realm
    path: /auth/htpasswd
http:
  addr: localhost:5000
  tls:
    certificate: /run/secrets/tracktech.ml-cert.pem
    key: /run/secrets/tracktech.ml-privkey.pem
  headers:
    X-Content-Type-Options: [nosniff]
health:
  storagedriver:
    enabled: true