version: 0.1
log:
  accesslog:
    disabled: true # Disable logging to stdout
  level: debug
  formatter: text # Left at default
  # hooks: https://docs.docker.com/registry/configuration/#hooks might be important for a later stage
storage:
  cache:
    blobdescriptor: inmemory
  filesystem: # Left at default
    rootdirectory: /var/lib/registry
    maxthreads: 100
  redirect: # Left at default
    disable: false
  maintenance:
    uploadpurging: # Left at default
      enabled: true
      age: 168h
      interval: 24h
      dryrun: false
    readonly:
      enabled: false # restart with enabled set to true for garbage collection, restart again with enabled set to false after garbage collection (false means the clients have write access to the registry)
auth: # excluding silly authentication as it might aswell not include auth at all
  # token: https://docs.docker.com/registry/configuration/#token
  htpasswd: # https://docs.docker.com/registry/configuration/#htpasswd
    realm: Registry Realm # space might cause issues
    path: /auth/htpasswd
# middleware: most likely not needed https://docs.docker.com/registry/configuration/#middleware
http:
  addr: localhost:5000
  tls:
    certificate: /run/secrets/tracktech.ml-cert.pem
    key: /run/secrets/tracktech.ml-privkey.pem
    clientcas:
      - /path/to/ca.pem
      - /path/to/another/ca.pem
    letsencrypt:
      cachefile: /path/to/cache-file
      email: emailused@letsencrypt.com
      hosts: [myregistryaddress.org]
  debug:
    addr: localhost:5001
    prometheus:
      enabled: true
      path: /metrics
  headers:
    X-Content-Type-Options: [nosniff]
  http2:
    disabled: false
notifications:
  events:
    includereferences: true
  endpoints:
    - name: alistener
      disabled: false
      url: https://my.listener.com/event
      headers: <http.Header>
      timeout: 1s
      threshold: 10
      backoff: 1s
      ignoredmediatypes:
        - application/octet-stream
      ignore:
        mediatypes:
           - application/octet-stream
        actions:
           - pull
# redis: I excluded redis https://docs.docker.com/registry/configuration/#redis
health:
  storagedriver:
    enabled: true
  # file:
    # file: /path/to/checked/file
  # http:
    # uri: http://server.to.check/must/return/200
  # tcp:
    # addr: redis-server.domain.com:6379