name: Cancel Workflow Action

on:
  pull_request:
    paths:
      - CameraProcessor/**
      - VideoForwarder/**
      - Interface/**
      - ProcessorOrchestrator/**

jobs:
  cancel_workflows:
    name: Cancel Workflow Action
    runs-on: self-hosted
    steps:
      - uses: styfle/cancel-workflow-action@0.6.0