name: Forwarder Build

on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/Forwarder_Build.yml
  pull_request:
    paths:
      - VideoForwarder/**

jobs:
  forwarder_build:
    name: Forwarder Build
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: recursive
      - name: Build
        run: docker-compose -f VideoForwarder/docker-compose.yml build --no-cache
      - name: Remove
        run: docker-compose -f VideoForwarder/docker-compose.yml down --rmi all
        if: ${{ always() }}
