name: Forwarder Build

on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/Forwarder_Build.yml
  pull_request:
    paths:
      - VideoForwarder/**

jobs:
  forwarder_build:
    name: Forwarder Build
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: recursive
      - name: Build
        run: docker build VideoForwarder
      - name: Build
        run: docker build VideoForwarder --target gpu
      - name: Prune images
        run: docker image prune --force --filter "until=24h"
        if: ${{ always() }}
