name: Forwarder Lint

on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/Forwarder_Lint.yml
  pull_request:
    paths:
      - VideoForwarder/**

jobs:
  forwarder_lint:
    name: Forwarder Lint
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: recursive
      - name: Build
        run: docker-compose -f ./VideoForwarder/compose/docker-compose_lint.yml up --build --no-start
      - name: Copy in pylintrc
        run: docker cp .pylintrc video-forwarder_container:/app
      - name: Copy in utility
        run: docker cp utility/__init__.py video-forwarder_container:/app/utility/
      - name: Copy in utility
        run: docker cp utility/pylint-plugins/. video-forwarder_container:/app/utility/pylint-plugins/
      - name: Run
        run: docker-compose -f ./VideoForwarder/compose/docker-compose_lint.yml up --exit-code-from video-forwarder
      - name: Remove
        run: docker-compose -f ./VideoForwarder/compose/docker-compose_lint.yml down --rmi all
        if: ${{ always() }}
      - name: Prune images
        run: docker image prune --force --filter "until=24h"
        if: ${{ always() }}
