name: Forwarder Unit Test

on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/Forwarder_Test_Unit.yml
  pull_request:
    paths:
      - VideoForwarder/**
    branches:
      - develop
      - master

jobs:
  forwarder_test_unit:
    name: Forwarder Unit Test
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: recursive
      - name: Build and run
        run: docker-compose -f ./VideoForwarder/compose/docker-compose_test_unit.yml up --build --exit-code-from video-forwarder
      - name: Copy xml coverage report
        run: docker cp video-forwarder_container:/app/coverage.xml coverage.xml
      - name: Codecov
        uses: codecov/codecov-action@v1.5.0
        with:
          files: coverage.xml
          flags: Forwarder
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: Remove
        run: docker-compose -f ./VideoForwarder/compose/docker-compose_test_unit.yml down --rmi all
        if: ${{ always() }}
      - name: Prune images
        run: docker image prune --force --filter "until=24h"
        if: ${{ always() }}
