name: Interface Lint

on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/Interface_Lint.yml
  pull_request:
    paths:
      - Interface/**

jobs:
  interface_lint:
    name: Interface Lint
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: recursive
      - name: Build and start
        run: docker-compose -f Interface/compose/docker-compose_lint.yml up --build --exit-code-from interface
      - name: Remove
        run: docker-compose -f Interface/compose/docker-compose_lint.yml down --rmi all
        if: ${{ always() }}
      - name: Prune images
        run: docker image prune --force --filter "until=24h"
        if: ${{ always() }}
