name: Interface-Orchestrator Integration Test

on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/Interface-Orchestrator.yml
  pull_request:
    paths:
      - Interface/**
      - ProcessorOrchestrator/**
    branches:
      - develop
      - master

jobs:
  interface-orchestrator:
    name: Interface-Orchestrator Integration Test
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: recursive
      - name: Build and run
        run: docker-compose -f Interface/compose/docker-compose_test_integration.yml up --build --exit-code-from interface
      - name: Copy xml coverage report
        run: docker cp interface_container:/react/coverage/clover.xml coverage.xml
      - name: Codecov
        uses: codecov/codecov-action@v1.5.0
        with:
          files: coverage.xml
          flags: Interface
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: Remove
        run: docker-compose -f Interface/compose/docker-compose_test_integration.yml down --rmi all
        if: ${{ always() }}
      - name: Prune images
        run: docker image prune --force --filter "until=24h"
        if: ${{ always() }}
