name: Interface Deploy
on:
  workflow_dispatch:
  push:
    paths:
      - Interface/**
      - .github/workflows/Interface_Deploy.yml
    branches:
      - develop
      - master
      - SPC-838-Deploy-docker-images-from-github-actions-

jobs:
  interface_deploy:
    name: Interface Deploy
    runs-on: self-hosted
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: "${{ secrets.DOCKERHUB_USERNAME }}"
          password: "${{ secrets.DOCKERHUB_TOKEN }}"
      - name: Build and push latest
        if: github.ref == 'refs/heads/develop'
        uses: docker/build-push-action@v2
        with:
          context: Interface
          push: true
          tags: "tracktech/interface:latest"
      - name: Build and push release
        if: github.ref == 'refs/heads/master'
        uses: docker/build-push-action@v2
        with:
          context: Interface
          push: true
          tags: "tracktech/interface:release"
