name: Interface Build

on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/Interface_Build.yml
  pull_request:
    paths:
      - Interface/**

jobs:
  interface_build:
    name: Interface Build
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: recursive
      - name: Build
        run: docker build --file Interface/Dockerfile
      - name: Prune images
        run: docker image prune --force --filter "until=24h"
        if: ${{ always() }}
