name: Interface Build

on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/Interface_Build.yml
  pull_request:
    paths:
      - Interface/**

jobs:
  interface_build:
    name: Interface Build
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: recursive
      - name: Build
        run: docker-compose -f Interface/docker-compose.yml build --no-cache
      - name: Remove
        run: docker-compose -f Interface/docker-compose.yml down --rmi all
        if: ${{ always() }}
      - name: Prune images
        run: docker image prune --force
        if: ${{ always() }}
