name: Orchestrator

on:
  push:
    paths:
      - .github/workflows/Orchestrator.yml
  pull_request:
    paths:
      - ProcessorOrchestrator/**

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: docker-compose -f ./ProcessorOrchestrator/docker-compose.yml build
      - name: Remove
        run: docker-compose -f ./ProcessorOrchestrator/docker-compose.yml rm

  test_unit:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Build and run
        run: docker-compose -f ./ProcessorOrchestrator/compose/docker-compose_test_unit.yml up --build --exit-code-from processor-orchestrator
      - name: Copy out report
        run: docker cp processor-orchestrator_container:/app/po-unit-report.xml po-unit-report.xml
      - name: Copy out coverage
        run: docker cp processor-orchestrator_container:/app/po_coverage_html po_coverage_html
      - name: Copy out coverage
        run: docker cp processor-orchestrator_container:/app/coverage.xml po-coverage.xml
      - name: Codecov
        uses: codecov/codecov-action@v1.5.0
        with:
          files: po-coverage.xml
          flags: Orchestrator
      - name: Remove
        run: docker-compose -f ./ProcessorOrchestrator/compose/docker-compose_test_unit.yml down

  test_integration:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Build and start
        run: docker-compose -f ./ProcessorOrchestrator/compose/docker-compose_test_integration.yml up --build --exit-code-from processor-orchestrator-integration-tests-service
      - name: Copy out report
        run: docker cp processor-orchestrator-integration-tests_container:/app/integration-report.xml integration-report.xml
      - name: Copy out coverage
        run: docker cp processor-orchestrator_container:/app/po_coverage_html po_coverage_html
      - name: Codecov
        uses: codecov/codecov-action@v1.5.0
        with:
          files: integration-report.xml
          flags: Orchestrator
      - name: Remove
        run: docker-compose -f ./ProcessorOrchestrator/compose/docker-compose_test_integration.yml down

  lint:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: docker-compose -f ./ProcessorOrchestrator/compose/docker-compose_lint.yml up --build --no-start
      - name: Copy in pylintrc
        run: docker cp .pylintrc processor-orchestrator_container:/app
      - name: Copy in utility
        run: docker cp utility/pylint_ignore.py processor-orchestrator_container:/app/utility/
      - name: Copy in utility
        run: docker cp utility/__init__.py processor-orchestrator_container:/app/utility/
      - name: Start
        run: docker-compose -f ./ProcessorOrchestrator/compose/docker-compose_lint.yml up --exit-code-from processor-orchestrator
      - name: Remove
        run: docker-compose -f ./ProcessorOrchestrator/compose/docker-compose_lint.yml down
