name: Orchestrator Integration Test

on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/Orchestrator_Test_Integration.yml
  pull_request:
    paths:
      - ProcessorOrchestrator/**
    branches:
      - develop
      - master

jobs:
  orchestrator_test_integration:
    name: Orchestrator Integration Test
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: recursive
      - name: Build and start
        run: docker-compose -f ./ProcessorOrchestrator/compose/docker-compose_test_integration.yml up --build --exit-code-from processor-orchestrator-integration-tests-service
      - name: Copy test report
        run: docker cp processor-orchestrator-integration-tests_container:/app/integration-report.xml integration-report.xml
      - name: Codecov
        uses: codecov/codecov-action@v1.5.0
        with:
          files: integration-report.xml
          flags: Orchestrator
      - name: Copy html coverage html
        run: docker cp processor-orchestrator_container:/app/po_coverage_html po_coverage_html
      - uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: po_coverage_html
      - name: Copy xml coverage report
        run: docker cp processor-orchestrator_container:/app/coverage.xml po-coverage.xml
      - name: Codecov
        uses: codecov/codecov-action@v1.5.0
        with:
          files: po-coverage.xml
          flags: Orchestrator
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: Remove
        run: docker-compose -f ./ProcessorOrchestrator/compose/docker-compose_test_integration.yml down --rmi all
        if: ${{ always() }}
      - name: Prune images
        run: docker image prune --force --filter "until=24h"
        if: ${{ always() }}
