name: Orchestrator Build
"on":
  workflow_dispatch: null
  push:
    paths:
      - ProcessorOrchestrator/**
      - .github/workflows/Orchestrator_Deploy.yml
    branches:
      - develop
      - master

jobs:
  orchestrator_deploy:
    name: Orchestrator Deploy
    runs-on: self-hosted
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: "${{ secrets.DOCKERHUB_USERNAME }}"
          password: "${{ secrets.DOCKERHUB_TOKEN }}"
      - name: Build and push latest
        if: github.ref == 'refs/heads/develop'
        uses: docker/build-push-action@v2
        with:
          context: ProcessorOrchestrator
          push: true
          tags: "tracktech/orchestrator:latest"
      - name: Build and push release
        if: github.ref == 'refs/heads/master'
        uses: docker/build-push-action@v2
        with:
          context: ProcessorOrchestrator
          push: true
          tags: "tracktech/orchestrator:release"
