name: Orchestrator Lint

on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/Orchestrator_Lint.yml
  pull_request:
    paths:
      - ProcessorOrchestrator/**

jobs:
  orchestrator_lint:
    name: Orchestrator Lint
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: recursive
      - name: Build
        run: docker-compose -f ./ProcessorOrchestrator/compose/docker-compose_lint.yml up --build --no-start
      - name: Copy in pylintrc
        run: docker cp .pylintrc processor-orchestrator_container:/app
      - name: Copy in pylint-utility
        run: docker cp utility/pylint-plugins/ video-forwarder_container:/app/utility/pylint-plugins/
      - name: Start
        run: docker-compose -f ./ProcessorOrchestrator/compose/docker-compose_lint.yml up --exit-code-from processor-orchestrator
      - name: Remove
        run: docker-compose -f ./ProcessorOrchestrator/compose/docker-compose_lint.yml down --rmi all
        if: ${{ always() }}
      - name: Prune images
        run: docker image prune --force --filter "until=168h"
        if: ${{ always() }}
