name: Processor Lint

on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/Processor_Lint.yml
  pull_request:
    paths:
      - CameraProcessor/**

jobs:
  processor_linting:
    name: Processor linting
    runs-on: self-hosted
    steps:
      - name: git remove yolor
        run: git rm -r --force CameraProcessor/processor/pipeline/detection/yolor || true
      - name: git remove yolov5 submodule
        run: git rm -r --force CameraProcessor/processor/pipeline/detection/yolov5 || true
      - name: git remove modules
        run: rm -rf .git/modules/* || true
      - name: add yolor
        run: git submodule add --name yolor https://github.com/UU-tracktech/yolor.git CameraProcessor/processor/pipeline/detection/yolor
      - name: add yolov5
        run: git submodule add --name yolov5 https://github.com/UU-tracktech/yolov5.git CameraProcessor/processor/pipeline/detection/yolov5
      - name: initialize
        run: git submodule update --init --recursive
      - uses: actions/checkout@v1
        with:
          submodules: true
      - name: Build service
        run: docker-compose -f ./CameraProcessor/compose/docker-compose_lint.yml up --build --no-start
      - name: Copy linting file into service
        run: docker cp .pylintrc camera-processor_lint_container:/app
      - name: Copy pylint_ignore.py into service
        run: docker cp utility/pylint_ignore.py camera-processor_lint_container:/app/utility
      - name: copy __init__.py into service
        run: docker cp utility/__init__.py camera-processor_lint_container:/app/utility
      - name: Start service
        run: docker-compose -f ./CameraProcessor/compose/docker-compose_lint.yml up --exit-code-from cameraprocessor
      - name: Stop service
        run: docker-compose -f ./CameraProcessor/compose/docker-compose_lint.yml down
        if: ${{ always() }}
