name: Processor Build

on:
  push:
    paths:
      - .github/workflows/Processor_Build.yml
  pull_request:
    paths:
      - CameraProcessor/**

jobs:
  processor_build:
    name: Processor build
    runs-on: [self-hosted, GPU]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build camera processor test service
        run: docker-compose -f ./CameraProcessor/docker-compose.yml build
      - name: Remove
        run: docker-compose -f ./CameraProcessor/docker-compose.yml rm
        if: ${{ always() }}
