name: Processor Unit Test

on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/Processor_Test_Unit.yml
  pull_request:
    paths:
      - CameraProcessor/**

jobs:
  processor_unit_test:
    name: Processor unit test
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Start unit test camera processor service
        run: docker-compose -f ./CameraProcessor/compose/docker-compose_test_unit.yml up --build --exit-code-from cameraprocessor
      - name: Copy html coverage report
        run: docker cp camera-processor_container:/app/coverage_html cp-coverage_html
      - name: Copy xml coverage report
        run: docker cp camera-processor_container:/app/coverage_html cp-coverage_html
      - name: Copy unit test report
        run: docker cp camera-processor_container:/app/coverage.xml coverage.xml
      - name: Stop service
        run: docker-compose -f ./CameraProcessor/compose/docker-compose_test_unit.yml down
        if: ${{ always() }}
      - name: Upload coverage artifact
        uses: actions/upload-artifact@v2
        with:
          name: cp-coverage_html
          path: output/cp-coverage.html
      - name: Upload unit test report artifact
        uses: actions/upload-artifact@v2
        with:
          name: cp-unit-report.xml
          path: output/cp-unit-report.xml
      - name: Codecov
        uses: codecov/codecov-action@v1.5.0
        with:
          files: coverage.xml
          flags: Processor
          token: ${{ secrets.CODECOV_TOKEN }}
