name: Processor Lint

on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/Processor_Lint.yml
  pull_request:
    paths:
      - CameraProcessor/**

jobs:
  processor_linting:
    name: Processor linting
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: recursive
      - name: Build service
        run: docker-compose -f ./CameraProcessor/compose/docker-compose_lint.yml up --build --no-start
      - name: Copy linting file into service
        run: docker cp .pylintrc camera-processor_lint_container:/app
      - name: Copy in utility __init__
        run: docker cp utility/__init__.py camera-processor_lint_container:/app/
      - name: Copy in utility
        run: docker cp utility/pylint-plugins/. camera-processor_lint_container:/app/utility/pylint-plugins/
      - name: Start service
        run: docker-compose -f ./CameraProcessor/compose/docker-compose_lint.yml up --exit-code-from cameraprocessor
      - name: Stop service
        run: docker-compose -f ./CameraProcessor/compose/docker-compose_lint.yml down --rmi all
        if: ${{ always() }}
      - name: Prune images
        run: docker image prune --force --filter "until=24h"
        if: ${{ always() }}
