name: Processor-Forwarder integration

on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/Processor-Forwarder.yml
  pull_request:
    paths:
      - CameraProcessor/**
      - VideoForwarder/**

jobs:
  processor_forwarder_integration_test:
    name: Camera Processor - Video Forwarder integration test
    runs-on: self-hosted
    steps:
      - name: git remove yolor
        run: git rm -r --force CameraProcessor/processor/pipeline/detection/yolor || true
      - name: git remove yolov5 submodule
        run: git rm -r --force CameraProcessor/processor/pipeline/detection/yolov5 || true
      - name: git remove modules
        run: rm -rf .git/modules/* || true
      - name: add yolor
        run: git submodule add --name yolor https://github.com/UU-tracktech/yolor.git CameraProcessor/processor/pipeline/detection/yolor
      - name: add yolov5
        run: git submodule add --name yolov5 https://github.com/UU-tracktech/yolov5.git CameraProcessor/processor/pipeline/detection/yolov5
      - name: initialize
        run: git submodule update --init --recursive
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Start service
        run: docker-compose -f ./CameraProcessor/compose/docker-compose+forwarder.yml up --build --exit-code-from camera-processor-test-service
      - name: Copy integration test report
        run: docker cp processor-forwarder-integration-test-container:/app/cp-vf-integration-report.xml cp-vf-integration-report.xml
      - name: Copy xml coverage report
        run: docker cp processor-forwarder-integration-test-container:/app/coverage.xml coverage.xml
      - name: Stop service
        run: docker-compose -f ./CameraProcessor/compose/docker-compose+forwarder.yml down
        if: ${{ always() }}
      - name: Upload integration test report artifact
        uses: actions/upload-artifact@v2
        with:
          name: cp-vf-integration-report.xml
          path: cp-vf-integration-report.xml
      - name: Codecov
        uses: codecov/codecov-action@v1.5.0
        with:
          files: coverage.xml
          flags: Processor
          token: ${{ secrets.CODECOV_TOKEN }}
