name: Processor Build

on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/Processor_Build.yml
  pull_request:
    paths:
      - CameraProcessor/**

jobs:
  processor_build:
    name: Processor build compose test
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: recursive
      - name: Build
        run: docker build --file CameraProcessor/Dockerfile
      - name: Prune images
        run: docker image prune --force --filter "until=24h"
        if: ${{ always() }}
