name: Processor Deploy
on:
  workflow_dispatch:
  push:
    paths:
      - CameraProcessor/**
      - .github/workflows/Processor_Deploy.yml
    branches:
      - develop
      - master
      - SPC-838-Deploy-docker-images-from-github-actions-

jobs:
  orchestrator_deploy:
    name: Processor Deploy
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: recursive
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: "${{ secrets.DOCKERHUB_USERNAME }}"
          password: "${{ secrets.DOCKERHUB_TOKEN }}"
      - name: Build and push latest
        if: github.ref == 'refs/heads/develop'
        uses: docker/build-push-action@v2
        with:
          context: CameraProcessor
          push: true
          tags: "tracktech/processor:latest"
      - name: Build and push release
        if: github.ref == 'refs/heads/master'
        uses: docker/build-push-action@v2
        with:
          context: CameraProcessor
          push: true
          tags: "tracktech/processor:release"
      - name: Build and push test
        if: github.ref == 'refs/heads/SPC-838-Deploy-docker-images-from-github-actions-'
        uses: docker/build-push-action@v2
        with:
          context: CameraProcessor
          push: true
          tags: "tracktech/processor:release"
