name: Processor Build

on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/Processor_Build.yml
  pull_request:
    paths:
      - CameraProcessor/**

# Not working because of the wrong compose version
#jobs:
#  processor_build:
#    name: Processor build
#    runs-on: [self-hosted, GPU]
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v2
#      - name: Build camera processor test service
#        run: docker-compose -f CameraProcessor/docker-compose.yml build
#      - name: Remove
#        run: docker-compose -f CameraProcessor/docker-compose.yml rm
#        if: ${{ always() }}

jobs:
  processor_build:
    name: Processor build compose test
    runs-on: self-hosted
    steps:
      - name: git remove yolor
        run: git rm -r --force CameraProcessor/processor/pipeline/detection/yolor || true
      - name: git remove yolov5 submodule
        run: git rm -r --force CameraProcessor/processor/pipeline/detection/yolov5 || true
      - name: git remove modules
        run: rm -rf .git/modules/* || true
      - name: add yolor
        run: git submodule add --name yolor https://github.com/UU-tracktech/yolor.git CameraProcessor/processor/pipeline/detection/yolor
      - name: add yolov5
        run: git submodule add --name yolov5 https://github.com/UU-tracktech/yolov5.git CameraProcessor/processor/pipeline/detection/yolov5
      - name: initialize
        run: git submodule update --init --recursive
      - uses: actions/checkout@v1
        with:
          submodules: true
      - name: Build camera processor test service
        run: docker-compose -f CameraProcessor/compose/docker-compose_test.yml build --no-cache
      - name: Remove
        run: docker-compose -f CameraProcessor/compose/docker-compose_test.yml rm
        if: ${{ always() }}
