name: forwarder
on: [pull_request, push]
jobs:
  build:
    runs-on: self-hosted
    steps:
      - run: cd ..
      - run: pwd
      - run: ls
      - run: docker-compose -f VideoForwarder/docker-compose.yml build
