name: forwarder
on:
  push:
    paths:
      - VideoForwarder/**
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - run: docker-compose -f VideoForwarder/docker-compose.yml build
  test_unit:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - run: docker-compose -f ./VideoForwarder/compose/docker-compose_test_unit.yml up --build --exit-code-from video-forwarder
      - run: docker cp video-forwarder_container:/app/vf-unit-report.xml vf-unit-report.xml
      - run: docker cp video-forwarder_container:/app/htmlcov vf-coverage_html
      - run: docker-compose -f ./VideoForwarder/compose/docker-compose_test_unit.yml down
